server:
  port: 8080

spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file: ../SpringBootDemo_DATA/logs/app.log
  level:
    root: INFO
